# Pytest settings

[pytest]
# Pytest configuration file

# Specify the test folder
testpaths = tests

# Minimum Python version
minversion = 7.0

# Add options - Adding HTML reporting here
addopts = -v --tb=short --html=report/report.html --self-contained-html

# markers
markers =
    Automation: Tests related to automation





